#!/bin/sh

GCC=gcc

mkdir -p ./objs
mkdir -p ./bins

[ "${1}" = "mips" ] && {
	export STAGING_DIR=/home/prog/openwrt/lede-all/new-lede-rb941/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16
	GCC=$STAGING_DIR/bin/mips-openwrt-linux-gcc
}

ret=0
$GCC ./mk_com.c -c -o ./objs/mk_com.o && \
$GCC ./main.c -o ./bins/mtpoe_ctrl ./objs/mk_com.o && \
ret=1

[ "${1}" = "mips" -a ${ret} -eq 1 ] && {
	echo "Do NetCat port port 1111"
	cat ./bins/mtpoe_ctrl | nc -l -p 1111 -q 1
}
